### ISSUE TITLE
Batch update

### ISSUE THREAD

**Issue by mradzinski** [Wackymax/CPOrm#1]
How shall I perform a bulk update using your library? Cheers and thanks!

**Comment by Wackymax** [comment]
Hi mradzinski,

You can currently do it as follows:

``` Java
            //Select the records to change
            List<User> users = Select.from(User.class).queryAsList();
            //Store update operation for batch
            List<ContentProviderOperation> operations = new ArrayList<>(users.size());

            for (User user : users) {

                //Change the values
                user.setUserName("New Username");

                //Prepare the update
                operations.add(CPOrm.prepareUpdate(user));
            }
            try {

                //Apply the changes
                CPOrm.applyPreparedOperations(operations);

            } catch (RemoteException e) {
                e.printStackTrace();
            } catch (OperationApplicationException e) {
                e.printStackTrace();
            }
```

Although I am not fond of it like this.  If you are willing to wait a while I will build in a new and better way of doing this.

**Comment by mradzinski** [comment]
I guess `prepareUpdate()` does a lot of heavy loading compared to creating my own ContentProviderOperation, so I'll probably end up using `getItemUri()` to get the Uri of my class, create my own operations, add them to a list and then apply everything invoking `applyPreparedOperations()`

**Comment by Wackymax** [comment]
Hi,

That is a good suggestion.  For the time being that would be better on performance yes.

**Comment by Wackymax** [comment]
Hi,

A new method has been added to the CPOrm class to make this a bit easier, you will still have to create the content resolver values, but the URI lookup and execution will be done for you now.
