### ISSUE TITLE
SQL Naming

### ISSUE THREAD

**Issue by npbenjohnson** [Wackymax/CPOrm#12]
It seems unnecessary and confusing to have sql columns switched to lowercase "_" seperated by default. I think it either shouldn't happen, or all query clauses should also convert column names automatically so the developer doesn't have to know sql naming details in order to use the orm.

**Comment by Wackymax** [comment]
Hi npbenjohnson,

Thank you for your suggestion.  The [new release](https://github.com/Wackymax/CPOrm/releases/tag/3.0.9) now has the capability to specify the naming provider.

All you have to do is specify your own COLUMN_NAME_CONVERTER in the TableDetails class before you initialize the ORM.
