### ISSUE TITLE
NPE querying View

### ISSUE THREAD

**Issue by otsenreDC** [Wackymax/CPOrm#13]
Hi Wackymax!

I got this error
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.auditoriamedica/com.company.auditoriamedica.activities.AuditsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String za.co.cporm.model.generate.TableDetails$ColumnDetails.getColumnName()' on a null object reference`

Running this piece of code
`long count = CPOrm.countAll(AuditClaimAffiliateView.class);`

On this View definition
`@Table
public class AuditClaimAffiliateView implements TableView {

    @Column
    private String code;
    @Column
    private String name = "";
    @Column
    private String lastName = "";
    @Column
    private Boolean autoPriority = false;
    @Column
    private Boolean priority = false;
    @Column
    private Date serviceDate = Calendar.getInstance().getTime();

    @Override
    public String getTableViewSql() {
        return "SELECT " +
                "AF." + Affiliate.Contract.COL_CODE + ", " +
                "AF." + Affiliate.Contract.COL_NAME + ", " +
                "AF." + Affiliate.Contract.COL_LAST_NAME + ", " +
                "AU." + Audit.Contract.COL_PRIORITY + ", " +
                "AU." + Audit.Contract.COL_AUTO_PRIORITY + ", " +
                "CL." + Claim.Contract.COL_SERVICE_DATE + " " +
                "FROM affiliate AF, audit AU, claim CL" + " " +
                "WHERE " +
                "AF." + Affiliate.Contract.COL_CODE + " = " +
                "AU." + Audit.Contract.COL_AFFILIATE_ID + " " +
                "AND " + " " +
                "CL." + Claim.Contract.COL_YEAR + " = " +
                "AU." + Audit.Contract.COL_YEAR + " AND " +
                "CL." + Claim.Contract.COL_BRANCH + " = " +
                "AU." + Audit.Contract.COL_BRANCH + " AND " +
                "CL." + Claim.Contract.COL_COMPANY + " = " +
                "AU." + Audit.Contract.COL_COMPANY + " AND " +
                "CL." + Claim.Contract.COL_SEQUENTIAL + " = " +
                "AU." + Audit.Contract.COL_SEQUENTIAL + ";";
    }
}`

The view is "well-formed". I tested the view created by CPOrm accesing through the adb shell.

Using
`compile 'za.co.cporm:CPOrm:3.0.6'`

And I tried the annotations from a previous issue you closed.

Thanks for your help.

**Comment by otsenreDC** [comment]
Its seems that `_id` is required. 
Added to the schema and it works smoothly.

**Comment by Wackymax** [comment]
Hi otsenreDC,

Apologies for the delay in my reply. I've been a bit busy.  Happy you managed to get it working however!  Hope the ORM treats you well :)
