### ISSUE TITLE
Support for multiple db

### ISSUE THREAD

**Issue by revant** [Wackymax/CPOrm#14]
Right now CPORM_CONFIG allows one configuration and only one provider is to be added.

Is it possible to add multiple providers and multiple databases?

I tried extending CPOrmContentProvider and adding that to manifest. It didn't work.

Is it possible?

Not an issue exactly, it's a query/feature request.

**Comment by Wackymax** [comment]
Hi Revant,

It would be possible but it would require some changes. I am a bit busy at
the moment but I will look at adding this in a future version.

Thank you for the suggestion.

**Comment by revant** [comment]
Thank you for considering feature request.

If you could tell me what all needs to be done, 
what you have in mind, 

I'll try to send a pull request if I can understand.

CPOrm is very easy to use! I'll be happy to contribute!

**Comment by Wackymax** [comment]
Hi,

I think we just have to move the config from the application meta into a
class loaded at startup. I started with that already in another branch, but
I don't think it is pushed.

The only other problem is the config is static, meaning only one can be
used per application instance.

That won't be to much of an issue if each provider has its own process, and
the ORM already supports querying different content providers.

I will put some thought into this and let you know ☺️
