### ISSUE TITLE
 java.lang.IllegalArgumentException: No row found with the key #

### ISSUE THREAD

**Issue by otsenreDC** [Wackymax/CPOrm#2]
The method **_public static <T> T findById(Class<T> object, long id)_** crashes _when the row is not found_.

I am using Select instead.

**Comment by Wackymax** [comment]
Hi otsenreDC,

That is the intended behavior.  If you would like to retrieve the record where it is nullable, can I suggest the following?

``` java
Select.from(RecordClass.class)
.whereEquals("_id", recordId)
.first();
```

**Comment by Wackymax** [comment]
Hi otsenreDC,

I decided to keep it like it is for now, if you query by id the ORM expects the records to exists.  I feel like this helps to catch errors earlier on during development, for queries where results can be null you can continue using the Select class.

**Comment by otsenreDC** [comment]
Cool, thanks!
