### ISSUE TITLE
Can't set NOT NULL on PRIMARY KEY column

### ISSUE THREAD

**Issue by pritambaral** [Wackymax/CPOrm#4]
SQLite [allows NULL values in a PRIMARY KEY column](https://www.sqlite.org/lang_createtable.html#primkeyconst) unless "_the column is an INTEGER PRIMARY KEY or the table is a WITHOUT ROWID table or the column is [explicitly] declared NOT NULL_".

This is undesirable in certain cases, where an INSERT may silently allow NULLs into a TEXT PRIMARY KEY column.

CPOrm currently does not honour `@Column`'s `required = true` if a column is declared a `@PrimaryKey`.

**Comment by Wackymax** [comment]
Thanks Pritambaral,

I will have a look at this and fix it

**Comment by Wackymax** [comment]
Hi pritambaral,

Thanks for the bug report.  I fixed the bug and it will be inlcuded with the next release.

**Comment by pritambaral** [comment]
@Wackymax in [the commit](15b227d) you limit it to `TEXT` columns only. SQLite doesn't default just _TEXT_ columns to nullable, it defaults any _non-INTEGER_ columns to nullable.

I think you should drop the check for `TEXT`, and allow setting `NOT NULL` for any column whatsoever. Simpler that way, and SQLite doesn't care if an `INTEGER` column is explictly set to `NOT NULL`

**Comment by Wackymax** [comment]
Ok thanks, I will do that instead then
