### ISSUE TITLE
database name

### ISSUE THREAD

**Issue by yeganehaym** [Wackymax/CPOrm#5]
hello and thanks for orm
i made a such class
`public class BackupConfig implements CPOrmConfiguration {

```
@Override
public String getDatabaseName() {

    return "backup.db";
}

@Override
public int getDatabaseVersion() {

    return 1;
}

@Override
public boolean isQueryLoggingEnabled() {

    return false;
}

@Override
public String upgradeResourceDirectory() {
    return null;
}

@Override
public List<Class<?>> getDataModelObjects() {
    List<Class<?>> domainObjects = new ArrayList<Class<?>>();
    domainObjects.add(BackupNotebookGroup.class);
    domainObjects.add(BackupNotebookPoem.class);
    domainObjects.add(BackupNotebookBook.class);

    domainObjects.add(BackupNotebookWriter.class);
    domainObjects.add(BackupNotebookPoemGroup.class);
    domainObjects.add(BackupNoteBookRhyme.class);

    return domainObjects;
}
```

}
`
and define it in manifest

`<meta-data
            android:name="CPORM_CONFIG"
            android:value="ir.plusteam.zekrekheyr.BackupHelper.Configs.BackupConfig" />`
but database name is application.db not backup.db and doesn't have tables

**Comment by Wackymax** [comment]
Hi yeganehaym,

It's always great to see people use the ORM, I am glad for your support.

Just a couple of questions, did you also specify the Authority meta tag, and also the android provider?  The database will only be created once you do your first query, so have a look at that as well.

**Comment by yeganehaym** [comment]
this my meta-tags
`       <meta-data
            android:name="MAPPING_FACTORY"
            android:value="om.cp.orm.example.MyMappingFactory" />
        
        <meta-data
            android:name="AUTHORITY"
            android:value="ir.plusteam" />
        

```
    <!-- Active Android -->


    <!-- providers -->
    <provider
        android:name="za.co.cporm.provider.CPOrmContentProvider"
        android:authorities="ir.plusteam"
        android:exported="false"
        android:process=":provider" />`
```

i tested again and db not created,

**Comment by Wackymax** [comment]
Can you see any errors in the log cat when you do Select.from(BackupNotebookGroup.class).queryAsList();

**Comment by yeganehaym** [comment]
when i insert:
Didn't find class "om.cp.orm.example.MyMappingFactory" on path: DexPathList[[zip file "/data/app/ir.plusteam.zekrekheyr-2.apk"],nativeLibraryDirectories=[/data/app-lib/ir.plusteam.zekrekheyr-2, /vendor/lib, /system/lib, /data/datalib]]

**Comment by Wackymax** [comment]
Ok, can you remove the mapping factory meta tag and try again?

**Comment by yeganehaym** [comment]
that's weird, i have error again but not log

**Comment by yeganehaym** [comment]
it's a loop error

**Comment by Wackymax** [comment]
I don't understand?  Can you provide more information?

**Comment by yeganehaym** [comment]
i haven't log about force close now after remove factory meta and i falled into force close loop

**Comment by Wackymax** [comment]
It is probably failing to create the database due to some configuration error.  It should say what the sql error was in the log files.

**Comment by yeganehaym** [comment]
with factory meta h have these too
Caused by: java.lang.IllegalArgumentException: Failed to create ModelFactory instance
 Caused by: java.lang.ClassNotFoundException: om.cp.orm.example.MyMappingFactory

**Comment by yeganehaym** [comment]
should i create a factory class too?

**Comment by yeganehaym** [comment]
i think i did a strange task

**Comment by yeganehaym** [comment]
om.cp.orm.example.MyMappingFactory ??

**Comment by yeganehaym** [comment]
i have an error too 
Caused by: java.lang.IllegalArgumentException: Failed load table details for object BackupNotebookBook

**Comment by yeganehaym** [comment]
```
@Table(tableName = "BackupNotebookBook")
public class BackupNotebookBook extends BackupNotebookSimpleBase {
}
```

father

```
public class BackupNotebookSimpleBase extends BackupNotebookBase {

    public static String TitleColumn="title";

    @Column(columnName = "title")
    String title;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}
```

and father

```
public class BackupNotebookBase {

    public static String IdColumn="id";

    @Column(columnName = "id",required = true,notifyChanges = false)
    @PrimaryKey
    @Unique
    long id;

    @Column(columnName = "new_id")
    long newId;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }


    public long getNewId() {
        return newId;
    }

    public void setNewId(long newId) {
        this.newId = newId;
    }
}
```

**Comment by Wackymax** [comment]
No, the mapping factory is only for advanced cases, you do not require it so do not specify the meta tag.  It would also be easier to extend CPDefaultRecord class, then you do not require the id primary column.

Have a look at the stack trace to see why it fails to load the table details for that object.

**Comment by Wackymax** [comment]
Is this working now?

**Comment by yeganehaym** [comment]
sorry, i was busy today
i cant use auto id, i want set id by myself
CPDefaultRecord make inherits out of order

**Comment by Wackymax** [comment]
Ok, no problem. 

Just make sure the column name is _id so android uses it correctly in list views. I think this is just a small configuration issue, most likely a spelling mistake or unsupported column type. Make sure to just use java primitives for now, or if you have custom classes to save create your own column mapper. The example project contains one for you to work from.

**Comment by yeganehaym** [comment]
is Date type supported?

**Comment by Wackymax** [comment]
Date and a few other common java types are supported yes. You can have a look in the za.co.cporm.map package for all the supported types.

**Comment by yeganehaym** [comment]
i limited tables to one and database is made
i will test tables one by one  to find out issue

**Comment by Wackymax** [comment]
Ok awesome. Be sure to increase the database version number as you add tables so it gets recreated.

**Comment by yeganehaym** [comment]
this table give me error now but i don't see problem in it

```
public class BackupNotebookGroup extends BackupNotebookSimpleBase {


    @Column(columnName = "list_order")
    int Listorder;

    @Column(columnName = "parent")
    long parent;

    public int getOrder() {
        return Listorder;
    }

    public void setOrder(int order) {
        this.Listorder = order;
    }

    public long getParent() {
        return parent;
    }

    public void setParent(long parent) {
        this.parent = parent;
    }
}
```

**Comment by Wackymax** [comment]
Does it have the @Table annotation?

**Comment by yeganehaym** [comment]
yeah
@Table(name = "BackupNotebookGroup")

**Comment by Wackymax** [comment]
That does seem strange, maybe one of the column names are a reserved word in sql?

**Comment by yeganehaym** [comment]
i changed them too already

**Comment by yeganehaym** [comment]
i think parent has a problem
there is list _order  in another table too , it was added

**Comment by yeganehaym** [comment]
worked now
i chnaged parent column name to myparent and worked

**Comment by Wackymax** [comment]
If you try changing it to list_parent?

**Comment by Wackymax** [comment]
Is there no log error messages giving you any clues?  SQL should tell you why it could not create the table.

**Comment by yeganehaym** [comment]
i have removed coumns
i've changed names,types, table name but it gives me error yet
no , i'm getting force close and its looping
but there is no any error log  or any log about this issue

**Comment by yeganehaym** [comment]
solved
it wasnt a solution but worked
i deleted the class and recreated it

**Comment by yeganehaym** [comment]
and sorry i wasted your time

**Comment by Wackymax** [comment]
That is extremely strange. Glad you got it working though. And no worries, I am just glad people are using the ORM, no time has been wasted. 

Can I close the issue?

**Comment by yeganehaym** [comment]
yes

**Comment by yeganehaym** [comment]
and thanks
it was kind of you
