### ISSUE TITLE
Saving and querying for NestedObjects in the db

### ISSUE THREAD

**Issue by nitishRathore** [Wackymax/CPOrm#6]
@Wackymax Hello i want to save some data into my db which i m getting in json format like this

{"id":"01",
"name":"XXXX YYYY",
"gender":"Female",
"educations":[
{
"degree_id":221,
"college_id":246,
"joining_year":"1212",
"graduation_year":"2000"
}
]
}

How should i model this data into a model class and how can i save data in one call itself.

Thanks in advance

**Comment by Wackymax** [comment]
Hi,

I would suggest making two model classes, one for the person, and then one for educations linking back to the person.  You can save it in one operation, but the orm cannot do it for you yet, I am planning that for the next release.  You can however use normal android content provider operations to save it all in one transaction.

https://developer.android.com/reference/android/content/ContentProviderOperation.html
http://www.grokkingandroid.com/better-performance-with-contentprovideroperation/

You can ask the ORM for the URI's for the objects by calling CPOrm.getItemUti({Model.class})

**Comment by nitishRathore** [comment]
@Wackymax when can i expect the next version??? any estimated time???

**Comment by Wackymax** [comment]
I cannot make any promises, but I will have a look over the weekend and see if I get some time to finish it. Then I will make a new release.

**Comment by Wackymax** [comment]
Hi nitishRathore,

Please try with the new release.  The [Wiki](https://github.com/Wackymax/CPOrm/wiki/Transactions-%28Experimental%29) shows you how to use the transactions.

**Comment by nitishRathore** [comment]
@Wackymax can u just put up an example code for the json model data which i have put up . I know i am asking a lot from you but it will really help for developers like me.

**Comment by nitishRathore** [comment]
@Wackymax i got the below error when i m trying to implement CPOrmTransaction
android.content.OperationApplicationException: wrong number of rows: 0

**Comment by Wackymax** [comment]
Hi nitish,

Sorry for the late reply.

I would model your data like this

``` java
@Table
public class Student extends CPDefaultRecord {

   @Column
   private String name;
   @Column
   private String gender;
}

@Table
public class Education extends CPDefaultRecord {

   @Column
    private long degreeId;
   @Column
    private long collegeId;
   @Column
    private String joiningYear;
   @Column
    private String graduationYear;
   @Column
   @References(Student.class)
    private long studentId;
}
```

Then to insert the data you could do this:

``` java
Student student = new Student("John","Male");
Education education = new Education(1, 1, 2003, 2006)

CPOrmTransaction transaction = new CPOrmTransaction();
transaction.add(student);
transaction.add(education);

try {
      transaction.commit();
} catch (Exception e) {
   Log.i(TAG, "Failed to apply transaction");
}
```

Make sure about the `@References` annotation as it is required for transactions.  Also make sure that your classes extend `CPDefaultRecord` otherwise transactions will not work.
