### ISSUE TITLE
"only updates, deletes, and asserts can have expected counts" Error On batch Insert

### ISSUE THREAD

**Issue by yeganehaym** [Wackymax/CPOrm#7]
hi 
this is my code for batch insert:

```
for (BackupNotebookGroup group : groups) {


            //Prepare the update
            operations.add(CPOrm.prepareInsert(group));
            records++;
            notifyObservers(records);
        }
        try {

            //Apply the changes
            CPOrm.applyPreparedOperations(operations);

        } catch (RemoteException e) {
            e.printStackTrace();
        } catch (OperationApplicationException e) {
            e.printStackTrace();
        }
```

i'm getting error at add operation line

**Comment by Wackymax** [comment]
Hi yeganehaym,

Can you try using the transaction class?

[https://github.com/Wackymax/CPOrm/wiki/Transactions-(Experimental)](https://github.com/Wackymax/CPOrm/wiki/Transactions-%28Experimental%29)

**Comment by yeganehaym** [comment]
yeah, i found this code
but my models are not extended the CPDefaultRecord

# 

however i am going to change my model
i have 2 orm in my app
active android control some tables and CPorm others
because i dont want backup all table in backup option
i just need some tables to backup or restore

**Comment by yeganehaym** [comment]
CPOrmTransaction is not exist in my version
maybe the gradle version is not updated?

**Comment by Wackymax** [comment]
Hi,

Please make sure you are using the latest version `compile 'za.co.cporm:CPOrm:3.0.7'

Also, what type of primary keys are you using on your records?

**Comment by yeganehaym** [comment]
auto increament but i'm not extend of CPDefaultRecord
i found the class now
