### ISSUE TITLE
depends on one or more Android Libraries but is a jar Error

### ISSUE THREAD

**Issue by yeganehaym** [Wackymax/CPOrm#8]
hi
i added ORM to java library but i got this error
`Error:Module 'ZekreKheyr:zekrmodel:unspecified' depends on one or more Android Libraries but is a jar`

**Comment by Wackymax** [comment]
Hi,

This seems like configuration issue with one of your android modules.  Please make sure that your module is set to a Android Library module.  I doubt CPOrm would be usable on a Java only project as it requires Android specific classes etc.

**Comment by yeganehaym** [comment]
module must be android module
