### ISSUE TITLE
v3.0.7 throws NullPointerException

### ISSUE THREAD

**Issue by otsenreDC** [Wackymax/CPOrm#9]
I started a new project and I was configuring it step by step. But when I start testing it and it throws a NullPointerException calling CPOrm#deleteAll

I changed the dependency to the v3.0.6 and the test passed. When I change back to v3.0.7 the test still passing. But if I unistall the app and run the test again for v3.0.7, it won't pass anymore.

**Comment by Wackymax** [comment]
Hi otsenreDC,

Can you maybe give me the stack trace for the null pointer exception? I am unable to reproduce the error on my side.

**Comment by otsenreDC** [comment]
Hi, 
Sorry, I forgot to send you the scenario. I'll send it to you asap.

**Comment by Wackymax** [comment]
Hi,

It seems like this is the root cause of the exception:  Caused by: java.lang.IllegalArgumentException: `Object does not have Table annotation`

Please make sure that the annotations are not discarded by progaurd, you can use the following to prevent this from happeneing

```
-keepattributes *Annotation*
-keepclassmembers class ** {
    @za.co.cporm.model.annotation.* *;
}

-keep class package.to.your.domain.classes.** { *; }
-keep class za.co.cporm.** { *; }
-dontwarn za.co.cporm.**
```
